---
title: "Run some basic R"
output: 
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Remove any potential lingering objects and data from RStudio when running a new script
```{r}
rm(list=ls())
```

## Which R version am I using?
```{r}
print(R.Version())
```

## Plot something in R
```{r}
set.seed(1)
x <- rnorm(100); y = rnorm(100)
plot(x,y)
```

## Plot something in R using ggplot
```{r}
data <- data.frame(x,y)

library(ggplot2)

ggplot(data) + 
  geom_point(aes(x=x,y=y)) +
  xlab('x-axis label') + ylab('y-axis label') +
  theme_classic()
```

## Create a vector and make simple manipulations
```{r}
# create vector_1
vector_1 <- c(6,7,8,9,10)

# print how many elements vector_1 has
length(vector_1)

# third element of vector_1
vector_1[3]

# second and fourth element of vector_1
vector_1[c(2,4)]

# access all but first element of vector_1
vector_1[-1]

# take elements of vector_1 less than 9
vector_1[vector_1<9]

# modify vector_1 2nd element
vector_1[2] <- -1
vector_1

# modify vector elements less than 9 to be -1
vector_1[vector_1 < 9] <- -1 
vector_1

# truncate vector first four elements
```

## Create and index a matrix
```{r}
# TO DO
```

## Using 'which' function 
```{r}
# TO DO
```

## Using R Operators (see https://www.datamentor.io/r-programming/operator/ for more info)
```{r}
# TO DO
```

## Create a function and use it
```{r}
# TO DO
```